challenges/urls.py
from django.urls import path
from . import views

app_name = "challenges"

urlpatterns = [
    path('<int:quiz_id>/', views.quiz_detail, name='quiz_detail'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
	path('', views.index, name="index"),
	path('signup/', views.signup, name="signup"),
	path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
	path('register/', views.register, name="register"),
	path('success_registration/', views.success_registration, name="success_registration"),
]

labs/urls.py
from django.urls import path

from . import views

from .views import LabDetailView

app_name = 'labs'

urlpatterns = [
	path('', views.labs, name="labs"),
	# path('lab/<int:lab_id>/', views.lab_detail, name='lab_detail'),
	path('<int:lab_id>/', LabDetailView.as_view(), name='lab_detail'),
	path('like_lab/', views.like_lab, name='like_lab'),
]

pro/urls.py
from django.urls import path

from . import views 

app_name = "pro"

urlpatterns = [
    path('', views.pro, name="pro"),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('labs/', include('labs.urls')),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('pro/', include('pro.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('challenges/', include('challenges.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

labs/models.py
from django.db import models
from django.contrib.auth.models import User

from challenges.models import Quiz

# Create your models here.
class LabTypeModel(models.Model):
    lab_type = models.CharField(max_length=20)

    def __str__(self):
        return self.lab_type


class Category(models.Model):
	name = models.CharField(max_length=100)

	class Meta:
		ordering = ('name',)
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.name

class VideoModel(models.Model):
	image = models.ImageField(upload_to="app_images", blank=True, null=True)
	category = models.ForeignKey(Category, related_name="video", on_delete=models.CASCADE)
	labs_type = models.ForeignKey(LabTypeModel, on_delete=models.CASCADE, null=True)
	name = models.CharField(max_length=100)
	content = models.TextField(blank=True, null=True)
	likes = models.ManyToManyField(User, related_name='video_likes', blank=True)
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		return self.name

	def like_count(self):
		return self.likes.count()

	def liked_users(self):
		return [user.username for user in self.likes.all()]

labs/views.py
from django.shortcuts import render, get_object_or_404

from . models import Category, VideoModel

from challenges.models import Quiz

from django.views import View

from django.http import JsonResponse


def labs(request):
    lessons = VideoModel.objects.all()[0:12]

    return render(request, "labs/labsMain.html", {
        'lessons': lessons,
    })


# def lab_detail(request, lab_id):
#     lab = get_object_or_404(VideoModel, pk=lab_id)

#     return render(request, "labs/lab_detail.html", {'lab': lab})

class LabDetailView(View):
    template_name_base = 'labs/lab_detail.html'
    template_name_type1 = 'labs/html_lab.html'
    template_name_CSStype = 'labs/css_lab.html'

    def get(self, request, lab_id):
        video = get_object_or_404(VideoModel, id=lab_id)
        print(video)
        lab_type = video.labs_type.lab_type if video.labs_type else None

        if lab_type == 'Type1':
            template_name = self.template_name_type1
        elif lab_type == "CSStype":
            template_name = self.template_name_CSStype
        else:
            template_name = self.template_name_base

        context = {'lab': video}
        return render(request, template_name, context)



def like_lab(request):
    if request.method == 'POST':
        lab_id = request.POST.get('lab_id')
        lab = VideoModel.objects.get(id=lab_id)

        user = request.user
        if user.is_authenticated:
            if user in lab.likes.all():
                lab.likes.remove(user)
                is_liked = False
            else:
                lab.likes.add(user)
                is_liked = True

            likes_count = lab.likes.count()
            return JsonResponse({'likes_count': likes_count, 'is_liked': is_liked})
    
    return JsonResponse({'error': 'Invalid request'})

labs/templates/labs/css_lab.html
{% extends 'labs/lab_detail.html' %}

{% block additional_content %}
    <p>Special Features Type 1: {{ lab.labs_type.lab_type }}</p>
    {% block additional_html %}
        <img class="w-1/2 my-2 max-[768px]:w-11/12" src="{{ lab.image.url }}" alt="HTML image"/>
        <div class="my-6">
            <div class="flex flex-col justify-start">
                <div class="py-2 border-b-4 border-dashed border-gray-600 self-start">
                    <h1 class="text-3xl my-2 font-bold text-white">Fillimi</h1>
                </div>
                <h1 class="text-2xl my-8 font-bold text-gray-500">Integrimi i CSS në HTML</h1>
                <div>
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Ekzistojnë <span class="text-blue-600 animate-pulse">tre</span> mënyra për integrimin e CSS në HTML dhe dizajnimin e tij.</p> 
                    <p class="text-[#d1d5db] max-[426px]:text-sm">Mënyrat për stilizimin e fajllit të HTML me anë të CSS janë këto: <span class="text-blue-600 animate-pulse">1. Inline styling(stilizimi në rresht)</span>, <span class="text-blue-600 animate-pulse">2. Internal styling(stilizimi brenda)</span> dhe <span class="text-blue-600 animate-pulse">3. External CSS(stilizimi jashtë)</span> </p>
                    <img class="my-4 w-3/4 max-[768px]:w-11/12 max-[426px]:w-full" src="/media/app_images/htmlpic1.png" alt="html picture" />
                </div>
                <h1 class="text-xl my-8 font-bold text-gray-500">Inline Styling</h1>
                <div>
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Inline styling (stilizimi në rresht) nënkupton stilizimin e përfshirë dhe vendosur në rresht të HTML tag, në mënyrë direkte, duke e përdorur  <span class="text-blue-600 animate-pulse">atributin <strong>style</strong></span></p> 
                    <p class="text-[#d1d5db] mb-2 max-[426px]:text-sm">Për të treguar këtë mënyrë të stilizimit , ne do stilizojmë një paragraf , dhe kjo bëhet si në figurë:</p>
                    <img class="my-4 w-3/4 max-[768px]:w-11/12 max-[426px]:w-full" src="/media/app_images/css1.png" alt="css 1 picture" />
                    <!--Test Code START-->
                    <!--Test code END-->
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Siç shihet ne kemi përdorur atributin style me anë të të cilit është bërë stilizimi i paragrafit.</p>
                    <p class="text-[#d1d5db] max-[426px]:text-sm"> Në kodin në figurë shohim se ne kemi definuar disa stile të ndryshme,  <span class="text-blue-600 animate-pulse">ngjyrën (color )</span> dhe <span class="text-blue-600 animate-pulse">madhësinë e tekstit ( font-size )</span></p>
                    <p class="text-[#d1d5db] max-[426px]:text-sm">Gjatë punës me CSS ne do i njohim dhe përdorim këto çifte <span class="text-blue-600 animate-pulse">vetish e vlerash</span>ku në rastin tonë për veti kemi ngjyrën ose madhësinë e teksit, e për vlerë kemi ngjyrën e kuqe , apo 30px.</p> 
                </div>
            </div>

            <h1 class="text-xl my-8 font-bold text-gray-500">Internal Styling</h1>
                <div>
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Internal styling (stilizimi i brendshëm) është stilizim i cili bëhet brenda fajllit të HTML, por në këtë rasr në një pjesë të <span class="text-blue-600 animate-pulse">veçantë të ndarë nga përmbajtja.</span></p> 
                    <p class="text-[#d1d5db] mb-2 max-[426px]:text-sm">Për të treguar këtë mënyrë të stilizimit , ne do stilizojmë një paragraf , dhe kjo bëhet si në figurë:</p>
                    <img class="my-4 w-3/4 max-[768px]:w-11/12 max-[426px]:w-full" src="/media/app_images/css2.png" alt="css 2 picture" />
                    <p class="text-[#d1d5db] mt-8">Etiketa <code class="bg-gray-800 text-white p-1 rounded font-mono text-lg my-4 ">
                        &lt;style&gt;&lt;/style&gt;
                    </code> është etiketë e cila vendoset në etiketën <span class="text-blue-600 animate-pulse">head</span> dhe përmban stilet e CSS të cilat integrohen në elementin e zgjedhur</p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Struktura e kësaj mënyre të stilizimit është se ajo fillon me <span class="text-blue-600 animate-pulse">selektorin(i cili në rastin tonë është p)</span>  dhe pastaj me kllapat , brenda të cilave shkruhen stilet</p> 
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Selektori mund të jetë vetë emri i etiketës, si në rastin tonë, mirëpo kjo do do zgjedhë për stilizim të gjitha paragrafet në faqe. Nëse dëshirojmë të zgjedhim grupe të veçanta të elementeve, atëherë do përdorim <span class="text-blue-600 animate-pulse">klasat dhe ID-të</span> sikur në shembullin në vijim</p> 
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Vini re se në këtë pjesë kemi vendosur disa veti dhe vlera të reja, shikoni në foto!</p> 

                </div>
                
            <h1 class="text-xl my-8 font-bold text-gray-500">External Styling</h1>

                <div>
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">External styling (stilizimi i jashtëm) është stilizim i cili përmban një file <span class="text-blue-600 animate-pulse">të veçantë të CSS</span> fajll i cili përdoret vetëm për përmbajtjen e stilizimit CSS.</p> 
                    <p class="text-[#d1d5db] mb-2 max-[426px]:text-sm">Për të treguar këtë mënyrë të stilizimit , ne do stilizojmë një paragraf , dhe kjo bëhet si në figurë:</p>
                    <img class="my-4 w-3/4 max-[768px]:w-11/12 max-[426px]:w-full" src="/media/app_images/css3.png" alt="css 3 picture" />
                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm"> Duhet të përmendim se ky fajll i ri i krijuar duhet të ketë  <span class="text-blue-600 animate-pulse">mbaresën .css</span> dhe duhet të lidhet me file HTML me anë të një etikete të re <span class="text-blue-600 animate-pulse">link tag</span></p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Kjo etiketë vendoset në pjesën head të programit dhe e drejton html te fajlli i kërkuar <span class="text-blue-600 animate-pulse">duke i lidhur mes vete.</span></p> 
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Nga kodi mund të shihni se ne kemi vendosur dy atribute të reja <span class="text-blue-600 animate-pulse">klasat dhe ID-të</span> të cilat vendosen te një element për ti veçuar stilet tek ai element i veçantë.</p> 
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Duhet të mbani mend se një element mund të ketë vetëm një ID , por mund të ketë më shumë klasa.</p> 
                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Në fajllin e CSS , për ta zgjedhur elementin e ID-së , përdorim # para emrit të dhënë, kurse për të selektuar klasën e vendosim një pikë .</p> 

                    <img class="my-4 w-3/4 max-[768px]:w-11/12 max-[426px]:w-full" src="/media/app_images/css33.png" alt="css 3 picture" />
                </div>
            
        </div>
    {% endblock %}
{% endblock %}

labs/templates/labs/html_lab.html
{% extends 'labs/lab_detail.html' %}

{% block additional_content %}
    <p>Special Features Type 1: {{ lab.labs_type.lab_type }}</p>
    {% block additional_html %}
        <img class="w-1/2 my-2 max-[426px]:w-full max-[426px]:my-6" src="{{ lab.image.url }}" alt="HTML image"/>
        <div class="my-6">
            <div class="flex flex-col justify-start">
                <div class="py-2 border-b-4 border-dashed border-gray-600 self-start">
                    <h1 class="text-3xl my-2 font-bold text-white">Fillimi</h1>
                </div>
                <h1 class="text-2xl my-8 font-bold text-gray-500">Krijimi i një fajlli HTML</h1>
                <div class="max-[426px]:text-sm">
                    <p class="text-[#d1d5db] mt-2">Për të filluar punën në HTML fillimish duhet të krijojmë një file me mbaresën ( extension ) <span class="text-blue-600 animate-pulse">.html</span>; </p> 
                    <p class="text-[#d1d5db]">Hapeni editorin tuaj të tekstit dhe menjëherë krijojeni një fajll të ri, ju mund ta ruani atë në një folder sipas dëshirës.</p>
                    <img class="my-4 w-3/4 max-[426px]:w-full" src="/media/app_images/htmlpic1.png" alt="html picture" />
                </div>
                <h1 class="text-2xl my-8 font-bold text-gray-500">Struktura e HTML</h1>
                <div class="max-[426px]:text-sm">
                    <p class="text-[#d1d5db] mt-2">HTML ka një strukturë e cila ndiqet gjatë krijimit të webfaqeve me të. Në <span class="text-blue-600 animate-pulse">HTML</span> i gjithë kodi organizohet me anë të llojeve të ndryshme të etiketave, për të cilat do flasim tani. </p> 
                    <p class="text-[#d1d5db] mb-2">Struktura themelore e çdo programi në HTML duket kështu:</p>
                    <!-- <img class="my-4 w-3/4" src="/media/app_images/htmlStructure2.png" alt="html picture" /> -->
                    <!--Test Code START-->
                    <pre class="border-2 border-slate-200 bg-gray-800 text-white p-2 rounded font-mono overflow-x-auto w-3/4 max-[1025px]:w-11/12">
                        <code class="language-html">
                          &lt;!DOCTYPE html&gt;
                          &lt;html lang="en"&gt;
                          &lt;head&gt;
                            &lt;meta charset="UTF-8"&gt;
                            &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
                            &lt;title&gt;Your Page Title&lt;/title&gt;
                          &lt;/head&gt;
                          &lt;body&gt;

                          &lt;/body&gt;
                          &lt;/html&gt;
                        </code>
                      </pre>
                    
                    <!--Test code END-->
                    <p class="text-[#d1d5db] mt-2">Tani shkurtimisht do njoftohemi me këto etiketa të HTML të cilat mund ti përdorni pastaj. Duhet të përmendim se në HTML kemi <strong class="text-blue-600 animate-pulse">dy</strong> dy lloje të etiketave: Etiketa të vetme, dhe etiketa në çift <span class="text-blue-600 animate-pulse">hapëse dhe mbyllëse.</span></p>
                    <p class="text-[#d1d5db]">Në kodin më lartë kemi paraqitur strukturën më të thjeshtë të një programi në HTML. Kjo strukturë është struktureë e përbashkët për të gjitha programet e tjera në HTML. Në këtë pjesë do njihemi me <span class="text-blue-600 animate-pulse">7 etiketat themelore në HTML.</span></p>
                    <p class="text-[#d1d5db]">Duhet të përmendim se struktura e një HTML dokumenti është e ngjajshme me atë të <span class="text-blue-600 animate-pulse">njeriut.</span>Sikur njerëzit, edhe dukumenti në HTML ka pjesën e kokës, trupit , të cilat pastaj degëzohen në pjesë tjera. Më poshtë njihuni me etiketat kryesore:</p> 
                </div>
            </div>

            <h1 class="text-2xl my-8 font-bold text-gray-500">Etiketa për tipin e dokumentit:</h1>
                <div>
                    <!-- <pre class="border-2 border-slate-200 bg-gray-800 text-white p-1 rounded font-mono overflow-x-auto w-1/2">
                        <code class="language-html">
                          &lt;!DOCTYPE html&gt;
                        </code>
                    </pre> -->
                    <code class="bg-gray-800 text-white p-4 rounded font-mono text-2xl my-2 max-[321px]:text-md max-[321px]:p-2">
                        &lt;!DOCTYPE html&gt;
                    </code>

                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm">Kjo etiketë është etiketë speciale, është etiketë <span class="text-blue-600 animate-pulse">e vetme, dhe quhet etiketa për tipin e dokumentit. </span></p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Kjo etiketë përdoret pët ti treguar shfletuesit ( browserit ) të përdoruesit versionin apo tipin e dokumentit të HTML që ne e përdorim. Nuk është e domosdoshme të përdoret , por është një praktikë e mirë për ta vendosur atë në krye të programit.</p> 
                </div>
                

                <h1 class="text-2xl my-8 font-bold text-gray-500">Etiketa html:</h1>
                <div>
                    <code class="bg-gray-800 text-white p-4 rounded font-mono text-2xl my-2 max-[426px]:p-1 max-[426px]:text-md max-[321px]:text-sm max-[321px]:p-2">
                        &lt;html lang="en"&gt;&lt;/html&gt;
                    </code>

                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm">Kjo etiketë është etiketa kryesore, brenda së cilës vendosen të gjitha etiketat tjera të programit. Është etiketë <span class="text-blue-600 animate-pulse">çift, sepse është hapëse dhe mbyllëse. </span></p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Etiketat çift, janë etiketa hapëse-mbyllëse, pra janë çift i etiketave. Kjo nuk vlen vetëm për këtë etiketë por edhe për të gjitha etiketat tjera të tipit të njejtë. Dallimi mes etiketës mbyllëse ndaj asaj hapëse është se etiketa mbyllëse e ka shenjën / përpara emrit të saj. Etiketa e html ndryshe quhet <span class="text-blue-600 animate-pulse">etiketë prind</span> e programmit sepse brenda saj vendosen tël gjitha tl tjerat.</p> 
                </div>


                <h1 class="text-2xl my-8 font-bold text-gray-500">Etiketa head:</h1>
                <div>
                    <code class="bg-gray-800 text-white p-4 rounded font-mono text-2xl my-2 ">
                        &lt;head&gt;&lt;/head&gt;
                    </code>

                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm">Në këtë etiketë vendosen të gjitha etiketat e tjera dhe të dhënat që kanë të bëjnë me<span class="text-blue-600 animate-pulse"> konfigurimin dhe rregullimin e programit. </span></p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Etiketa head është poashtu etiketë çift, dhe vendoset brenda etiketës html, pra etiketa html është  <span class="text-blue-600 animate-pulse">etiketë prind</span> e etiketës head.</p> 
                </div>

                <h1 class="text-2xl my-8 font-bold text-gray-500">Etiketat meta:</h1>
                <div>
                    <code class="bg-gray-800 text-white p-2 rounded font-mono text-xl my-2 max-[426px]:p-1 max-[426px]:text-sm">
                            &lt;meta charset="UTF-8"&gt;
                            &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
                    </code>

                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm">Etiketat meta, të cilat janë etiketa të vetme, gjithmonë vendosen brenda etiketës head, dhe kanë të bëjnë me rregullimin e <span class="text-blue-600 animate-pulse"> konfigurimin dhe paraqitjen e të dhënave të nevojshme për faqen. </span></p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Etiketat meta përdoren për të përcaktuar karakteret e të dhënave, për të përcaktuar fjalët kyq të faqes, emrin e autorit apo për ta bërë faqen e përshtatshme për responsivitet etj.</p> 
                </div>

                <h1 class="text-2xl my-8 font-bold text-gray-500">Etiketa title:</h1>
                <div>
                    <code class="bg-gray-800 text-white p-4 rounded font-mono text-2xl my-2 max-[321px]:text-sm max-[321px]:p-2">
                        &lt;title&gt;&lt;/title&gt;
                    </code>

                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm">Etiketa çift title është etiketë e cila poashtu vendoset në etiketen head, prandaj head është "prind i saj". </p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Etiketa title përdoret për përcaktimin e titullit të dritares, e cila paraqitet në dritaren e shfletuesit.</p> 
                </div>

                <h1 class="text-2xl my-8 font-bold text-gray-500">Etiketa body:</h1>
                <div>
                    <code class="bg-gray-800 text-white p-4 rounded font-mono text-2xl my-2 ">
                        &lt;body&gt;&lt;/body&gt;
                    </code>

                    <p class="text-[#d1d5db] mt-8 max-[426px]:text-sm">Etiketa body, njejtë sikur etiketa head, është etiketë çift e cila është në të njejtin rend me etiketën head, pra të dy këto etiketa shumë të rëndësishme janë brenda etiketës kryesore html.</p> 

                    <p class="text-[#d1d5db] mt-2 max-[426px]:text-sm">Etiketa body është një etiketë <span class="text-blue-600 animate-pulse">shumë e rëndësishme</span>, e cila për dallim nga etiketa head e cila përmban të gjitha të dhënat e konfigurimit të webfaqes, kjo etiketë përmban <span class="text-blue-600 animate-pulse">gjithë përmbajtjen e faqes, pra vetë trupin e saj.</span></p> 
                </div>
        </div>

        <!-- <div class="my-8 mt-24 px-6 py-6 flex flex-row justify-evenly items-center w-3/4">
            <button style="font-family: 'Roboto Condensed', sans-serif;" class="font-bold text-md p-2.5 cursor-pointer outline-none border-none text-white bg-green-500 transition-all duration-200 ease-in-out hover:bg-green-700 focus:bg-teal-700">
                <a href="{% url 'core:register' %}">MËSO MË SHUMË</a>
            </button>
            <button style="font-family: 'Roboto Condensed', sans-serif;" class="font-bold text-md p-2.5 cursor-pointer outline-none border-none text-white bg-green-500 transition-all duration-200 ease-in-out hover:bg-green-700 focus:bg-teal-700">
                <a href="{% url 'challenges:quiz_detail' quiz_id=1 %}">USHTRIM</a>
            </button>
        </div> -->
    {% endblock %}
{% endblock %}

labs/templates/labs/lab_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lab.name }} | Puddle{% endblock %}

{% block content %}
<div>
    <div class="flex flex-row gap-6">
        <div class="py-6 px-6 w-3/4 max-[426px]:w-full">
            <h1 class="text-4xl font-bold my-4 text-gradient max-[1025px]:text-3xl">{{ lab.name }}</h1>
            <p class="text-[#d1d5db] my-4 max-[1025px]:text-sm ">{{ lab.content }}</p>
        
            {% block additional_html %}{% endblock %}
        
        </div>
    
        <div id="minimap-container" class="fixed right-0 flex flex-col gap-6 px-4 py-4 text-gray-500 font-semibold mx-2 my-8 max-[768px]:mx-0 max-[768px]:gap-2 max-[700px]:hidden">
           
        </div>
    </div>

    <div class="flex justify-start items-start">
        <div class="my-8 px-6 py-6 flex flex-row justify-center items-center">
            <img id="like-icon" class="w-14 cursor-pointer" src="/media/app_images/heart1.png" alt="Like image" onclick="likeLab('{{ lab.id }}')"/>

            <span id="like-count">{{ lab.likes.count }}</span> 
        </div>
    </div>

    <div class="my-8 mt-24 px-6 py-6 flex flex-row justify-evenly items-center w-3/4 max-[376px]:w-full max-[376px]:px-2">
        <button style="font-family: 'Roboto Condensed', sans-serif;" class="whitespace-nowrap font-bold text-md p-2.5 cursor-pointer outline-none border-none text-white bg-green-500 transition-all duration-200 ease-in-out hover:bg-green-700 focus:bg-teal-700 max-[376px]:p-2 max-[376px]:text-sm">
            <a href="{% url 'core:register' %}">MËSO MË SHUMË</a>
        </button>
        <button style="font-family: 'Roboto Condensed', sans-serif;" class="font-bold text-md p-2.5 cursor-pointer outline-none border-none text-white bg-green-500 transition-all duration-200 ease-in-out hover:bg-green-700 focus:bg-teal-700 max-[376px]:p-2 max-[376px]:text-sm">
            <a href="{% url 'challenges:quiz_detail' quiz_id=lab.quiz.id %}">USHTRIM</a>
        </button>
    </div>

</div>
{% endblock %}

labs/templates/labs/labsMain.html
{% extends 'core/base.html' %}

{% block title %}Labs | Puddle{% endblock %}

{% block content %}
<div class="mt-12 py-6 px-6 flex flex-col justify-center items-center">
	<h1 class="my-2 text-3xl font-semibold text-white">LABS</h1>
	<p class="text-sm text-gray-500 font-thin mb-12 max-[320px]:text-center">Mesime, blog dhe video te ndryshme.</p>
	<div class="w-24 bg-gray-500 rounded-xl h-1"></div>
</div>

<div class="col-span-3 px-8 py-8 max-[320px]:my-8 max-[320px]:mb-12">
	<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
	{% for lesson in lessons %}
		<div class="hover:transform hover:scale-105 transition-transform">
			<a class="#">
				<div>
					{% if lesson.image %}
						<img src="{{ lesson.image.url }}" class="rounded-t-xl image-fit" />
					{% else %}
						<p>No image available</p>
					{% endif %}
				</div>

				<div class="p-6 bg-gray-800 rounded-b-xl max-[1024px]:p-4">
					<h2 class="text-xl my-2">{{ lesson.name }}</h2>
					<p class="my-4 text-gray-500 text-sm" id="truncatedContent">{{ lesson.content }}</p>

					<form class="flex flex-row gap-4">
						<button class="outline-none border-none rounded-xl p-2 text-xs text-blue-500 bg-black">#{{ lesson.category }}</button>
						<button class="outline-none border-none text-md bg-blue-500 text-white font-semibold px-4 py-2 transition-all hover:bg-blue-700 focus:bg-blue-700">
							<a href="{% url 'labs:lab_detail' lab_id=lesson.id %}" class="whitespace-nowrap max-[1024px]:text-sm ">Read more</a>
						</button>
					</form>
				</div>
			</a>
		</div>
	{% endfor %}
	</div>
</div>
{% endblock %}