blog/urls.py
from django.urls import path
from . import views 

app_name = "blog"

urlpatterns = [
	path('', views.PostList.as_view(), name="blog"),
	path('addPost/', views.add_post, name="add"),
	path('<slug:slug>/', views.DetailedView.as_view(), name="detail"),
	path('<int:pk>/delete/', views.delete_post, name="delete"),
]

pro/urls.py
from django.urls import path

from . import views 

app_name = "pro"

urlpatterns = [
    path('', views.pro, name="pro"),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('labs/', include('labs.urls')),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('pro/', include('pro.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('challenges/', include('challenges.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models

from django.contrib.auth.models import User

# STATUS=((0, "Draft"), (1, "Published"))

class Post(models.Model):

	STATUS = (
        (0, "Draft"),
        (1, "Published"),
    )
	
	title = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(unique=True, max_length=255)
	content = models.TextField()
	author = models.ForeignKey(User, related_name="blog_user", on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	status = models.IntegerField(choices=STATUS, default=0)

	def save(self, *args, **kwargs):
        
		if not self.slug:
			self.slug = slugify(self.title)
        
		super().save(*args, **kwargs)

	class Meta:
		ordering = ['-created_at']

	def __str__(self):
		return self.title

blog/forms.py
from django import forms
from . models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'slug', 'content', 'status',)
    
    title = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Titulli i postimit',
        'class': 'text-black w-5/6 py-4 px-6 rounded-xl max-[375px]:w-full'
    }), label=False)

    slug = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Slug',
        'class': 'text-black w-5/6 py-4 px-6 rounded-xl max-[375px]:w-full'
    }), label=False)

    content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Shkruani përmbajtjen këtu',
        'class': 'text-black w-5/6 py-4 px-6 rounded-xl max-[375px]:w-full',
        'rows': 5,
    }), label=False)

    status = forms.ChoiceField(choices=Post.STATUS, widget=forms.Select(attrs={
        'class': 'my-2 mb-8 text-black w-1/12 py-4 px-6 rounded-xl max-[1025px]:w-1/2',
    }), label=False)


    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . models import Post
from django.views import generic
from django.contrib.auth.decorators import login_required

from .forms import PostForm

class PostList(generic.ListView):
	queryset = Post.objects.filter(status=1).order_by('-created_at')
	template_name = "blog/post.html"

class DetailedView(generic.DetailView):
	model = Post
	template_name = "blog/post_detail.html"
	slug_field = "slug"

@login_required
def delete_post(request, pk):
	post = get_object_or_404(Post, pk=pk, author=request.user)
	post.delete()

	return redirect('blog:blog')

@login_required
def add_post(request):
	
	if request.method == "POST":
		form = PostForm(request.POST)

		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.author = request.user
			new_post.save()
			return redirect('blog:blog') 
	else:
		form = PostForm()

	return render(request, 'blog/postForm.html', {'form': form})

blog/templates/blog/post.html
{% extends "core/base.html" %}

{% block title %}Blog | Main{% endblock %}

{% block content %}
	<div class="flex flex-row ">

		<div class="col-md-8 mt-6 left grow">
			{% for post in post_list %}
				<div class="bg-gray-800 rounded-xl p-7 w-3/4 mb-6">
					<div>
						<h2 class="mb-2 text-2xl font-semibold">{{ post.title }}</h2>
						<p class="mb-4 text-md font-thin text-gray-600">{{ post.author }} | {{ post.created_at }}</p>
						<p class="mb-8 text-lg font-thin text-gray-400">{{ post.content|slice:":200" }}</p>	
						<div class="flex items-center justify-between">
							<a class="cursor-pointer outline-none border-none rounded-xl p-3 bg-blue-500 font-semibold transition-all duration-300 ease-in-out hover:bg-blue-300 focus:bg-blue-300" href="{% url 'blog:detail' slug=post.slug %}">Read More</a>
							{% if request.user == post.author %}
								<a class="cursor-pointer outline-none border-none rounded-xl p-3 bg-red-500 font-semibold transition-all duration-300 ease-in-out hover:bg-red-300 focus:bg-red-300" href="{% url 'blog:delete' post.id %}">Delete</a>
							{% endif %}
						</div>	
					</div>
				</div>
			{% endfor %}
		</div>

		<div class="flex-none">
			<button class="rounded-xl outline-none border-none bg-blue-500 text-white font-semibold px-4 py-2 transition-all duration-300 ease-in-out hover:bg-blue-700 focus:bg-blue-700">
				<a href="{% url 'blog:add' %}">Add a new post +</a>		
			</button>
		</div>

	</div>
{% endblock %}

blog/templates/blog/postForm.html
{% extends "core/base.html" %}

{% block title %}Add Post{% endblock %}

{% block content %}
    <h1 class="my-2 mb-12 font-semibold text-3xl">Add a new blog post</h1>
    <form action="." method="POST">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
			<div class="mb-3 p-6 bg-red-100 rounded-xl">
				{% for field in forms %}
					{{ field.errors }}
				{% endfor %}

				{{ form.non_field_errors }}
			</div>
		{% endif %}
        
        <button type="submit" class="cursor-pointer outline-none border-none rounded-xl p-3 bg-blue-500 font-semibold transition-all duration-300 ease-in-out hover:bg-blue-300 focus:bg-blue-300">Add Post</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "core/base.html" %}

{% block title %} Post {% endblock %}

{% block content %}
	<div class="bg-gray-800 rounded-xl p-6 w-3/4">
		<div class="col-md-8 mt-3 left">
				<div class="mb-4">
					<div>
						<h2 class="mb-2 text-2xl font-semibold">{{ object.title }}</h2>
						<p class="mb-4 text-md font-thin text-gray-600">{{ post.author }} | {{ post.created_at }}</p>
						<p class="mb-8 text-lg font-thin text-gray-400">{{ object.content|safe }}</p>	
					</div>
				</div>
		</div>
	</div>
{% endblock %}