blog/urls.py
from django.urls import path
from . import views 

app_name = "blog"

urlpatterns = [
	path('', views.PostList.as_view(), name="blog"),
	path('addPost/', views.add_post, name="add"),
	path('<slug:slug>/', views.DetailedView.as_view(), name="detail"),
	path('<int:pk>/delete/', views.delete_post, name="delete"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
	path('', views.index, name="index"),
	path('signup/', views.signup, name="signup"),
	path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
	path('register/', views.register, name="register"),
	path('success_registration/', views.success_registration, name="success_registration"),
]

courses/urls.py
from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
	path('', views.courses, name="courses"),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.index, name="index"),
    # path('inbox/', views.inbox, name="inbox"),
    path('users/', views.users, name="users"),
    path('profile/showcase/', views.profile_showcase, name="profile_showcase"),
    path('profile/modify/', views.profile_modify, name="profile_modify"),
    path('salesForm/', views.sales, name="sales"),
    path('salesData/', views.salesData, name="salesData"),
    path('labsForm/', views.labsForm, name="labsForm"),
    path('labsData/', views.labsData, name="labsData"),
    path('coursesForm/', views.coursesForm, name="coursesForm"),
    path('coursesData/', views.coursesData, name="coursesData"),
    
    path('priceForm/', views.priceForm, name="priceForm"),
    path('priceData/', views.priceData, name="priceData"),

    path('newQuizForm/', views.newQuizForm, name="newQuizForm"),
    path('quizData/', views.quizData, name="quizData"),

    path('questionForm/', views.questionForm, name="questionForm"),
    path('questionData/', views.questionData, name="questionData"),

    path('answerForm/', views.answerForm, name="answerForm"),
    path('answerData/', views.answerData, name="answerData"),

    path('newRegistrationForm/', views.registrationForm, name="registrationForm"),
    path('registrationData/', views.registrationData, name="registrationData"),

    path('userAnswersData/', views.userAnswerData, name="userAnswerData"),

    path('labScoreData/', views.labScoreData, name="labScoreData"),

    path('categoryLabForm/', views.categoryLabForm, name="categoryLabForm"),
    path('categoryLabData/', views.categoryLabData, name="categoryLabData"),

    path('categoryCourseForm/', views.categoryCourseForm, name="categoryCourseForm"),
    path('categoryCourseData/', views.categoryCourseData, name="categoryCourseData"),

    path('postsData/', views.postsData, name="postsData"),

    path('labTypeForm/', views.labTypeForm, name="labTypeForm"),
    path('labTypeData/', views.labTypeData, name="labTypeData"),

    path('blogPosts/', views.PostList.as_view(), name="blog"),
	path('addPost/', views.add_post, name="add"),
	path('<slug:slug>/', views.DetailedView.as_view(), name="detail"),
	path('<int:pk>/delete/', views.delete_post, name="delete"),
]

labs/urls.py
from django.urls import path

from . import views

from .views import LabDetailView

app_name = 'labs'

urlpatterns = [
	path('', views.labs, name="labs"),
	# path('lab/<int:lab_id>/', views.lab_detail, name='lab_detail'),
	path('<int:lab_id>/', LabDetailView.as_view(), name='lab_detail'),
	path('like_lab/', views.like_lab, name='like_lab'),
]

pro/urls.py
from django.urls import path

from . import views 

app_name = "pro"

urlpatterns = [
    path('', views.pro, name="pro"),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('labs/', include('labs.urls')),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('pro/', include('pro.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('challenges/', include('challenges.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PriceForCoursesModel(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    timestamp = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.price
    
    def save(self, *args, **kwargs):
        
        super().save(*args, **kwargs)


class RegistrationModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=150)
    age = models.IntegerField()
    email = models.EmailField(max_length=125)
    phone_number = models.CharField(max_length=100, blank=True)
    students_interst = models.TextField()
    from_where = models.TextField(blank=True, null=True)
    user_bio = models.TextField(blank=True, null=True)

core/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import RegistrationModel

class LoginForm(AuthenticationForm):
	
	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder':'Your username', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder':'Your password', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

class SignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')


	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder':'Your username', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

	email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder':'Your email', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

	password1 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder':'Your password', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

	password2 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder':'Repeat your password', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))


class RegistrationForm(forms.ModelForm):
	class Meta:
		model = RegistrationModel
		fields = ("full_name", "age", "email", "phone_number", "students_interst", "from_where", "user_bio",)
	

	full_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'text-black w-full px-3 py-2 mb-2 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors',
            'placeholder': 'Emri dhe mbiemri'
        })
    )
	
	age = forms.IntegerField(
        required=True,
        widget=forms.NumberInput(attrs={'class': 'text-black w-full py-2 px-4 text-black border-2 border-gray-300 rounded-xl my-2', 'placeholder': 'Mosha juaj'}),
        label='Mosha juaj',  
        min_value=5, 
    )

	email = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'text-black w-full px-3 py-2 mb-2 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors',
            'placeholder': 'Email'
        })
    )

	phone_number = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'text-black w-full px-3 py-2 mb-2 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors',
            'placeholder': 'Phone Number(Opsionale)'
        })
    )

	students_interst = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Interesi juaj ne programim dhe cka ju pelqen rreth tij',
        'rows': 5,
        'class': 'text-black resize-none w-full px-3 py-2 my-2 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors'
    }), label=False)

	from_where = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Prej nga keni dëgjuar për ne ( Opsionale )',
        'rows': 5,
        'class': 'text-black resize-none w-full px-3 py-2 my-2 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors'
    }), label=False)

	user_bio = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Shkruani dica rreth vetes tuaj ( Opsionale )',
        'rows': 5,
        'class': 'text-black resize-none w-full px-3 py-2 my-2 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 transition-colors'
    }), label=False)

core/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required

from django.http import HttpResponse

from .forms import SignupForm, RegistrationForm

from dashboard.models import SalesData

from . models import PriceForCoursesModel


def index(request):
	sales_data = SalesData.objects.values_list('percentage_value', flat=True).last()

	last_price = PriceForCoursesModel.objects.values_list('price', flat=True).order_by('-id').first()
	current_price = last_price - ( last_price * int(sales_data) / 100 )

	return render(request, 'core/index.html', {
		'sales_data': sales_data,
		'last_price': last_price,
		'current_price': current_price,
	})

def success_registration(request):
	return render(request, "core/success_registration.html")

def signup(request):

	if request.method == "POST":
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form,
	})

@login_required
def register(request):

	if request.method == "POST":
		form = RegistrationForm(request.POST)

		if form.is_valid():
			form_data_instance = form.save(commit=False)
			form_data_instance.user = request.user 
			form_data_instance.save()

			return redirect("core:success_registration")
	
	else:
		form = RegistrationForm()
	
	return render(request, "core/register.html", {
		'form': form,
	})

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}{% endblock %}</title>

		<script src="https://cdn.tailwindcss.com"></script>

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Inclusive+Sans&family=Rubik&display=swap" rel="stylesheet">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Inclusive+Sans&family=Roboto+Condensed&display=swap" rel="stylesheet">

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prism-themes/themes/prism-material-oceanic.css">
  		<script defer src="https://cdn.jsdelivr.net/npm/prismjs@1.25.0"></script>

		<script src="{% static 'mobileNav.js' %}" defer></script>
		<script src="{% static 'truncateText.js' %}" defer></script>
		<script src="{% static 'minimap.js' %}" defer></script>

		<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

		<style>
			body {font-family: 'Rubik', sans-serif;}

			.non-visible {
				opacity: 0;
				transition: all 2s;
				filter: blur(5px);
			}

			.show {
				opacity: 1;
				filter: blur(0);
			}

			.image-fit {
			    width: 100%;
			    height: 100%;
			    object-fit: cover;
			}

			/* Code for responsivity of the navbar */
			#mobile-menu {
                transition: transform 0.6s ease-in-out;
            }

            #mobile-menu.hidden {
                transform: translateX(100%);
            }

			#nav-btn {
				z-index: 999;
			}

			/*End*/

			/* Test code below about the register page*/

			/*remove custom style*/
			.circles{
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
				overflow: hidden;
			}
			.circles li{
				position: absolute;
				display: block;
				list-style: none;
				width: 20px;
				height: 20px;
				background: rgba(255, 255, 255, 0.2);
				animation: animate 25s linear infinite;
				bottom: -150px;  
			}
			.circles li:nth-child(1){
				left: 25%;
				width: 80px;
				height: 80px;
				animation-delay: 0s;
			}
			
			
			.circles li:nth-child(2){
				left: 10%;
				width: 20px;
				height: 20px;
				animation-delay: 2s;
				animation-duration: 12s;
			}
			
			.circles li:nth-child(3){
				left: 70%;
				width: 20px;
				height: 20px;
				animation-delay: 4s;
			}
			
			.circles li:nth-child(4){
				left: 40%;
				width: 60px;
				height: 60px;
				animation-delay: 0s;
				animation-duration: 18s;
			}
			
			.circles li:nth-child(5){
				left: 65%;
				width: 20px;
				height: 20px;
				animation-delay: 0s;
			}
			
			.circles li:nth-child(6){
				left: 75%;
				width: 110px;
				height: 110px;
				animation-delay: 3s;
			}
			
			.circles li:nth-child(7){
				left: 35%;
				width: 150px;
				height: 150px;
				animation-delay: 7s;
			}
			
			.circles li:nth-child(8){
				left: 50%;
				width: 25px;
				height: 25px;
				animation-delay: 15s;
				animation-duration: 45s;
			}
			
			.circles li:nth-child(9){
				left: 20%;
				width: 15px;
				height: 15px;
				animation-delay: 2s;
				animation-duration: 35s;
			}
			
			.circles li:nth-child(10){
				left: 85%;
				width: 150px;
				height: 150px;
				animation-delay: 0s;
				animation-duration: 11s;
			}
			@keyframes animate {
			
				0%{
					transform: translateY(0) rotate(0deg);
					opacity: 1;
					border-radius: 0;
				}
			
				100%{
					transform: translateY(-1000px) rotate(720deg);
					opacity: 0;
					border-radius: 50%;
				}
			
				}
				.triangle{
					border-top:60rem solid #fff;
					border-left:25rem solid transparent;
				}

				/* .text-gradient {
					background: -webkit-linear-gradient(#f97316, #eab308);
  					-webkit-background-clip: text;
  					-webkit-text-fill-color: transparent;
				} */

				.text-gradient {
					background: -webkit-linear-gradient(#f97316, #eab308);
					background: linear-gradient(#f97316, #eab308); /* Standard syntax */
					-webkit-background-clip: text;
					background-clip: text; /* Standard property */
					-webkit-text-fill-color: transparent;/*
					text-fill-color: transparent;  Standard property */
				}


		</style>

	</head>
	<body class="bg-[#0C121B]">

		<nav class="text-white py-8 px-6 flex justify-between items-center">
			<a href="#" class="font-bold max-[768px]:text-sm">DevMastery</a>

			<div class="space-x-12 max-[1024px]:space-x-8 max-[768px]:space-x-5 max-[600px]:space-x-2">
				<div class="flex flex-row items-center min-[426px]:hidden">
					<button id="nav-btn" class="bg-transparent p-8">
						<span class="bar bg-white block h-1 w-8 mb-1"></span>
						<span class="bar bg-white block h-1 w-8 mb-1"></span>
						<span class="bar bg-white block h-1 w-8"></span>
					</button>
				</div>

				<a href="{% url 'pro:pro' %}" class="max-[426px]:hidden text-teal-500 rounded-lg font-semibold p-1 text-md border-2 border-teal-500 bg-transparent hover:scale-110 transition-transform duration-300 ease-in-out max-[768px]:text-sm max-[600px]:text-xs">PRO</a>
				<a href="{% url 'core:index' %}" class="max-[426px]:hidden font-semibold text-md transition-all duration-300 ease-in-out hover:text-gray-300 hover:scale-110 max-[768px]:text-sm max-[600px]:text-xs">Home</a>
				<a href="{% url 'labs:labs' %}" class="max-[426px]:hidden font-semibold text-md transition-all duration-300 ease-in-out hover:text-gray-300 hover:scale-110 max-[768px]:text-sm max-[600px]:text-xs">Labs</a>
				<a href="{% url 'courses:courses' %}" class="max-[426px]:hidden font-semibold text-md transition-all duration-300 ease-in-out hover:text-red-400 max-[768px]:text-sm max-[600px]:text-xs">Courses</a>
				<a href="{% url 'core:register' %}" class="max-[426px]:hidden font-semibold text-md transition-all duration-300 ease-in-out hover:text-red-400 max-[768px]:text-sm max-[600px]:text-xs">Register</a>
				<a href="{% url 'dashboard:profile_showcase' %}" class="max-[426px]:hidden font-semibold text-md transition-all duration-300 ease-in-out hover:text-red-400 max-[768px]:text-sm max-[600px]:text-xs">Profile</a>
				<a href="{% url 'blog:blog' %}" class="max-[426px]:hidden font-semibold text-md transition-all duration-300 ease-in-out hover:text-red-400 max-[768px]:text-sm max-[600px]:text-xs">Blog</a>

				<a href="{% url 'core:login' %}" class="max-[426px]:hidden p-2 text-md font-bold text-black bg-white outline-none border-none transition-all duration-300 ease-in-out hover:bg-purple-700 focus:bg-purple-700 hover:text-white focus:text-white max-[768px]:text-xs max-[768px]:p-1">LOGIN</a>

				<a href="{% url 'core:signup' %}" class="max-[426px]:hidden p-2 text-md font-bold text-black bg-white outline-none border-none transition-all duration-300 ease-in-out hover:bg-purple-700 focus:bg-purple-700 hover:text-white focus:text-white max-[768px]:text-xs max-[768px]:p-1">SIGN UP</a>
			</div>
		</nav>

		<!--Mobile menu-->
		<div id="mobile-menu" class="hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-90 z-50">
            <div class="w-full h-full flex justify-center flex-col items-center text-3xl text-gray-400 font-[400]">
                <a href="{% url 'pro:pro' %}" class="my-4 transition-all duration-300 ease-in-out hover:text-white">PRO</a>
                <a href="{% url 'labs:labs' %}" class="my-4 transition-all duration-300 ease-in-out hover:text-white">LABS</a>
                <a href="{% url 'courses:courses' %}" class="my-4 transition-all duration-300 ease-in-out hover:text-white">COURSES</a>
                <a href="{% url 'blog:blog' %}" class="my-4 transition-all duration-300 ease-in-out hover:text-white">BLOG</a>
                <a href="{% url 'core:login' %}" class="my-4 transition-all duration-300 ease-in-out hover:text-white">LOGIN</a>
                <a href="{% url 'core:signup' %}" class="my-4 transition-all duration-300 ease-in-out hover:text-white">SIGNUP</a>
            </div> 
        </div>

		<div class="px-4 py-4 text-white">
			{% block content %}{% endblock %}
		</div>

		<footer class="py-6 px-6 flex justify-center bg-[#0C121B]">

			<div class="rounded-xl py-6 m-4 bg-slate-400"></div>

			<div class="text-sm text-slate-500 font-semibold">
				{% if user.is_authenticated %}
                    <p class="py-2">Welcome, {{ user.username }}!</p>
                {% endif %}
				<p class="py-2">Join the discord: <strong>Processing and creating now</strong></p>
				<p class="py-2">Need Help: <strong>devmastery17@gmail.com</strong></p>
				<div class="py-2 flex flex-row justify-evenly">
					<svg class="w-8" aria-hidden="true" data-prefix="fab" data-icon="youtube" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" class="svgyoutube  "><path fill="currentColor" d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"></path></svg>
					<svg class="w-8" aria-hidden="true" data-prefix="fab" data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" class="svggithub "><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>
				</div>
				<p class="font-bold py-2">DEV MASTERY</p>
				<p class="py-2 text-xs">Copyright © 2023</p>
			</div>	
		</footer>
		
		<script src="{% static 'script.js' %}"></script>
		<script src="{% static 'scroll.js' %}"></script>
		<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

		<script>

			$.ajaxSetup({
					headers: {
						'X-CSRFToken': '{{ csrf_token }}',
					}
			});

			function likeLab(labId) {
					$.ajax({
						type: 'POST',
						url: '{% url "labs:like_lab" %}',
						data: {'lab_id': labId},
						success: function (data) {
							$('#like-count').text(data.likes_count);

							if (data.is_liked) {
								$('#like-icon').attr('src', '/media/app_images/heartred.png');
							} else {
								$('#like-icon').attr('src', '/media/app_images/heart1.png');
							}
						},
						error: function (data) {
							console.log('Error:', data);
						}
					});
			}

		</script>
	</body>
</html>

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="w-1/2 p-6 mx-auto my-6 bg-black text-white rounded-xl max-[768px]:w-3/4 max-[426px]:w-5/6 max-[320px]:w-full">
		<h1 class="mb-6 text-3xl font-semibold">Log in</h1>

		<form method="post" action=".">
			{% csrf_token %}

			<div class="mb-3">
				<label class="inline-block mb-2">Username</label><br>
				{{ form.username }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Password</label><br>
				{{ form.password }}
			</div>

			{% if form.errors or form.non_field_errors %}
				<div class="mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %} 
						{{ field.errors }}
					{% endfor %}

					{{ form.non_field_errors }}
				</div>
		    {% endif %}

			<button class="mt-2 p-2 text-md font-bold bg-blue-700 outline-none border-none transition-all duration-300 ease-in-out hover:bg-blue-400 focus:bg-blue-400">Submit</button>
		</form>
	</div>
{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
	<div class="w-1/2 p-6 mx-auto my-6 bg-black text-white rounded-xl max-[768px]:w-3/4 max-[426px]:w-5/6 max-[320px]:w-full">
		<h1 class="mb-6 text-3xl font-semibold">Sign up</h1>

		<form method="post" action=".">
			{% csrf_token %}

			<div class="mb-3">
				<label class="inline-block mb-2">Username</label><br>
				{{ form.username }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Email</label><br>
				{{ form.email }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Password</label><br>
				{{ form.password1 }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Repeat password</label><br>
				{{ form.password2 }}
			</div>

			{% if form.errors or form.non_field_errors %}
				<div class="mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %} 
						{{ field.errors }}
					{% endfor %}

					{{ form.non_field_errors }}
				</div>
		    {% endif %}

			<button class="mt-2 p-2 text-md font-bold bg-blue-700 outline-none border-none transition-all duration-300 ease-in-out hover:bg-blue-400 focus:bg-blue-400">Submit</button>
		</form>
	</div>
{% endblock %}

core/templates/core/success_registration.html
{% extends "core/base.html" %}

{% block title %}Regjistrimi yt u krye{% endblock %}

{% block content %}
<div class="flex flex-col justify-center items-center w-full bg-green-200 p-4 my-4 rounded-md max-[426px]:p-6 max-[426px]:mt-8 max-[426px]:text-center">
    <h1 class="text-emerald-600 text-6xl font-bold my-8 max-[321px]:text-5xl">Regjistrimi juaj u krye me sukses</h1>
    <p class="text-emerald-400 text-xl font-semibold my-8 max-[321px]:text-lg">Regjistrimi juaj u ruajt dhe do merrni përgjigje nga ne  <span class="text-emerald-600 animate-pulse">shpejtë.</span></p>
    <a href="{% url 'core:index' %}" class="my-2 mb-8 outline-none border-none text-lg px-6 py-2 font-semibold text-white bg-teal-500 rounded-lg transition-all duration-300 ease-in-out hover:bg-teal-700">
        Kthehu pas
    </a>
</div>
{% endblock %}